<#
.SYNOPSIS
    Restores the Moldflow Mobile PostgreSQL database from a backup archive.

.DESCRIPTION
    Restores tables and schema from a .dump file generated by pg_dump.

.PARAMETER BackupFile
    Path to the .dump file to restore. If omitted, uses the newest backup in BackupDir.
#>

[CmdletBinding()]
param(
    [string]$BackupFile,
    [string]$BackupDir = "C:\MF\MoldflowSynergyPlugin\backups",
    [string]$PgRestorePath = "C:\Program Files\PostgreSQL\17\bin\pg_restore.exe",
    [string]$DbHost = "127.0.0.1",
    [int]$DbPort = 5432,
    [string]$DbUser = "moldflow_app",
    [string]$DbName = "moldflow_mobile",
    [string]$DbPassword = "Moldflow123"
)

Write-Host "============================================================" -ForegroundColor Cyan
Write-Host " Moldflow Mobile - Database Restore Utility                " -ForegroundColor Cyan
Write-Host "============================================================" -ForegroundColor Cyan

# 1. Determine backup file
if (-not $BackupFile) {
    $latest = Get-ChildItem -Path $BackupDir -Filter "moldflow_mobile_backup_*.dump" | Sort-Object LastWriteTime -Descending | Select-Object -First 1
    if (-not $latest) {
        Write-Error "No backup files found in $BackupDir"
        exit 1
    }
    $BackupFile = $latest.FullName
}

if (-not (Test-Path -Path $BackupFile)) {
    Write-Error "Backup file not found: $BackupFile"
    exit 1
}

Write-Host "[1/2] Selected Backup: $BackupFile" -ForegroundColor Yellow

# 2. Check pg_restore.exe
if (-not (Test-Path -Path $PgRestorePath)) {
    Write-Error "pg_restore.exe not found at $PgRestorePath"
    exit 1
}

# 3. Execute pg_restore
Write-Host "[2/2] Restoring to database '$DbName'..." -ForegroundColor Yellow

$env:PGPASSWORD = $DbPassword

$restoreArgs = @(
    "-h", $DbHost,
    "-p", $DbPort.ToString(),
    "-U", $DbUser,
    "-d", $DbName,
    "--clean",
    "--if-exists",
    "-v",
    $BackupFile
)

try {
    $proc = Start-Process -FilePath $PgRestorePath -ArgumentList $restoreArgs -NoNewWindow -Wait -PassThru
    if ($proc.ExitCode -eq 0) {
        Write-Host "      [OK] Database restoration completed successfully!" -ForegroundColor Green
    } else {
        Write-Warning "pg_restore completed with exit code $($proc.ExitCode) (some warnings during object drop are expected)."
    }
}
finally {
    Remove-Item env:PGPASSWORD -ErrorAction SilentlyContinue
}

Write-Host "============================================================" -ForegroundColor Cyan
Write-Host " Restore Finished at $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss') " -ForegroundColor Green
Write-Host "============================================================" -ForegroundColor Cyan
